'use strict';

// Generated by Unit Test Generator (pipeline run, bug batch 001).
// Scope: ONLY the code changed in context/bugs/001/fix-summary.md —
//   - isAdmin (removal of the hardcoded 'admin123' token, comparison moved
//     to process.env.ADMIN_TOKEN using a constant-time crypto.timingSafeEqual
//     comparison, with type/length guards).
//
// Independent/Repeatable (FIRST): process.env.ADMIN_TOKEN is saved in
// beforeEach and restored in afterEach so no test's mutation of the env var
// leaks into another test or into other test files in the suite, and each
// test sets exactly the env state it needs.

const { test, describe, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const { isAdmin } = require('../src/auth');

describe('isAdmin', () => {
  let originalAdminToken;

  beforeEach(() => {
    originalAdminToken = process.env.ADMIN_TOKEN;
  });

  afterEach(() => {
    if (originalAdminToken === undefined) {
      delete process.env.ADMIN_TOKEN;
    } else {
      process.env.ADMIN_TOKEN = originalAdminToken;
    }
  });

  test('returns true for the correct token when ADMIN_TOKEN is set', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin('super-secret-token'), true);
  });

  test('returns false for an incorrect token of the same length', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin('super-secret-tokan'), false);
  });

  test('returns false for a token of a different (shorter) length', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin('short'), false);
  });

  test('returns false for a token of a different (longer) length', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin('super-secret-token-but-much-longer'), false);
  });

  test('returns false for a non-string token (number)', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin(12345), false);
  });

  test('returns false for a non-string token (null)', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin(null), false);
  });

  test('returns false for a non-string token (undefined)', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin(undefined), false);
  });

  test('returns false for a non-string token (object)', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin({ token: 'super-secret-token' }), false);
  });

  test('returns false for any token when ADMIN_TOKEN is unset', () => {
    delete process.env.ADMIN_TOKEN;
    assert.equal(isAdmin('anything'), false);
  });

  test('returns false for an empty-string token when ADMIN_TOKEN is unset', () => {
    delete process.env.ADMIN_TOKEN;
    assert.equal(isAdmin(''), false);
  });

  test('regression — the old hardcoded default token "admin123" no longer grants access when ADMIN_TOKEN is a different value', () => {
    process.env.ADMIN_TOKEN = 'super-secret-token';
    assert.equal(isAdmin('admin123'), false);
  });

  test('regression — the old hardcoded default token "admin123" no longer grants access when ADMIN_TOKEN is unset', () => {
    delete process.env.ADMIN_TOKEN;
    assert.equal(isAdmin('admin123'), false);
  });
});
