'use strict';

// Generated by Unit Test Generator (pipeline run, bug batch 001).
// Scope: ONLY the code changed in context/bugs/001/fix-summary.md —
//   - calculateTotal (off-by-one loop start fix)
//   - filterByMonth (UTC + 1-indexed month fix)
// Existing tests/utils.test.js is left untouched; this file adds regression
// and boundary coverage for the same two functions.

const test = require('node:test');
const assert = require('node:assert/strict');
const { calculateTotal, filterByMonth } = require('../src/utils');

// ---------------------------------------------------------------------------
// calculateTotal — Change 1: loop used to start at i = 1, skipping the first
// expense. Fixed to start at i = 0.
// ---------------------------------------------------------------------------

test('calculateTotal: regression — single-element list is not skipped (would be 0 under the pre-fix off-by-one loop)', () => {
  const result = calculateTotal([{ amount: 15.75 }]);
  assert.equal(result, 15.75);
});

test('calculateTotal: regression — first expense in a multi-item list contributes to the sum', () => {
  const expenses = [
    { amount: 5 },
    { amount: 5 },
    { amount: 5 },
  ];
  // Under the pre-fix loop (i = 1), the first item is skipped and this would
  // total 10 instead of 15.
  assert.equal(calculateTotal(expenses), 15);
});

test('calculateTotal: edge case — empty list returns 0', () => {
  assert.equal(calculateTotal([]), 0);
});

test('calculateTotal: edge case — single element list equals that element amount', () => {
  assert.equal(calculateTotal([{ amount: 42.4 }]), 42.4);
});

test('calculateTotal: rounds the sum to two decimal places', () => {
  const expenses = [{ amount: 0.1 }, { amount: 0.2 }];
  assert.equal(calculateTotal(expenses), 0.3);
});

// ---------------------------------------------------------------------------
// filterByMonth — Change 2: used to compare local getFullYear()/getMonth()
// (0-indexed) against a 1-indexed `month` argument. Fixed to use
// getUTCFullYear()/getUTCMonth() + 1, matching the 1-indexed convention and
// making the comparison timezone-independent.
// ---------------------------------------------------------------------------

test('filterByMonth: regression — January (month=1) matches an item dated in January (pre-fix getMonth()===1 would compare 0===1 and always fail)', () => {
  const expenses = [
    { id: 1, date: '2026-01-15T12:00:00Z' },
    { id: 2, date: '2026-02-15T12:00:00Z' },
  ];
  const jan = filterByMonth(expenses, 2026, 1);
  assert.deepEqual(jan.map((e) => e.id), [1]);
});

test('filterByMonth: regression — December (month=12) matches an item dated in December (pre-fix getMonth()===12 would compare 11===12 and always fail)', () => {
  const expenses = [
    { id: 1, date: '2026-12-25T12:00:00Z' },
    { id: 2, date: '2026-11-25T12:00:00Z' },
  ];
  const dec = filterByMonth(expenses, 2026, 12);
  assert.deepEqual(dec.map((e) => e.id), [1]);
});

test('filterByMonth: edge case — empty list returns an empty list', () => {
  assert.deepEqual(filterByMonth([], 2026, 3), []);
});

test('filterByMonth: edge case — single element list matching the month/year is returned', () => {
  const expenses = [{ id: 1, date: '2026-05-04T08:00:00Z' }];
  assert.deepEqual(filterByMonth(expenses, 2026, 5), expenses);
});

test('filterByMonth: edge case — single element list not matching the month/year is excluded', () => {
  const expenses = [{ id: 1, date: '2026-05-04T08:00:00Z' }];
  assert.deepEqual(filterByMonth(expenses, 2026, 6), []);
});

test('filterByMonth: excludes an item whose month matches but whose year does not', () => {
  const expenses = [
    { id: 1, date: '2024-06-15T12:00:00Z' },
    { id: 2, date: '2025-06-15T12:00:00Z' },
    { id: 3, date: '2026-06-15T12:00:00Z' },
  ];
  const result = filterByMonth(expenses, 2026, 6);
  assert.deepEqual(result.map((e) => e.id), [3]);
});

test('filterByMonth: UTC boundary — a timestamp late on the last day of March in UTC (2026-03-31T23:30:00Z) is counted as March, not April', () => {
  const expenses = [{ id: 1, date: '2026-03-31T23:30:00Z' }];

  const march = filterByMonth(expenses, 2026, 3);
  assert.deepEqual(march.map((e) => e.id), [1]);

  const april = filterByMonth(expenses, 2026, 4);
  assert.deepEqual(april, []);
});
